version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - backend
    volumes:
      - mongodb-data:/data/db

  db-manager-service:
    build:
      context: ./db-manager-service
      dockerfile: Dockerfile
    container_name: db-manager-service
    networks:
      - backend
      - internal
    environment:
      MONGO_URI: "mongodb://mongodb:27017"

  employee-service:
    build:
      context: ./employee-service
      dockerfile: Dockerfile
    container_name: employee-service
    networks:
      - internal

  payslip-service:
    build:
      context: ./payslip-service
      dockerfile: Dockerfile
    container_name: payslip-service
    networks:
      - internal

  time-log-service:
    build:
      context: ./time-log-service
      dockerfile: Dockerfile
    container_name: time-log-service
    networks:
      - internal

  file-generator-service:
    build:
      context: ./file-generator-service
      dockerfile: Dockerfile
    container_name: file-generator-service
    networks:
      - internal

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    networks:
      - internal

  api-gateway-service:
    build:
      context: ./api-gateway-service
      dockerfile: Dockerfile
    container_name: api-gateway-service
    networks:
      - frontend
      - internal

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    networks:
      - frontend

networks:
  backend:
    name: backend-network
  internal:
    name: internal-network
  frontend:
    name: frontend-network

volumes:
  mongodb-data:
    name: mongodb-data-volume
