version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb-data:/data/db
    networks:
      - backend

  db-manager-service:
    build:
      context: ./db-manager-service
    container_name: db-manager-service
    environment:
      MONGO_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}"
    depends_on:
      - mongodb
    networks:
      - backend
      - internal

  employee-service:
    build:
      context: ./employee-service
    container_name: employee-service
    depends_on:
      - db-manager-service
    networks:
      - internal

  payslip-service:
    build:
      context: ./payslip-service
    container_name: payslip-service
    depends_on:
      - db-manager-service
    networks:
      - internal

  time-log-service:
    build:
      context: ./time-log-service
    container_name: time-log-service
    depends_on:
      - db-manager-service
    networks:
      - internal

  file-generator-service:
    build:
      context: ./file-generator-service
    container_name: file-generator-service
    depends_on:
      - db-manager-service
    networks:
      - internal

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    depends_on:
      - api-gateway-service
    networks:
      - internal

  api-gateway-service:
    build:
      context: ./api-gateway-service
    container_name: api-gateway-service
    depends_on:
      - employee-service
      - payslip-service
      - time-log-service
      - file-generator-service
      - auth-service
    networks:
      - frontend
      - internal

  client:
    build:
      context: ./client
    container_name: client
    depends_on:
      - api-gateway-service
    networks:
      - frontend

networks:
  backend:
    name: backend-network
  internal:
    name: internal-network
  frontend:
    name: frontend-network

volumes:
  mongodb-data:
    name: mongodb-data-volume
