apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
      - name: api-gateway-service
        image: localhost:5000/api-gateway:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: myregistrykey
