apiVersion: v1
kind: Service
metadata:
  name: bitbucket
  namespace: development
spec:
  type: LoadBalancer
  ports:
  - port: 7990
    targetPort: 7990
    protocol: TCP
    name: http
  selector:
    app: bitbucket
