apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitbucket
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitbucket
  template:
    metadata:
      labels:
        app: bitbucket
    spec:
      containers:
      - name: bitbucket
        image: atlassian/bitbucket-server:latest
        ports:
        - containerPort: 7990
        env:
        - name: BITBUCKET_HOME
          value: "/var/atlassian/application-data/bitbucket"
        volumeMounts:
        - name: bitbucket-data
          mountPath: "/var/atlassian/application-data/bitbucket"
      volumes:
      - name: bitbucket-data
        persistentVolumeClaim:
          claimName: bitbucket-data
