apiVersion: apps/v1
kind: Deployment
metadata:
  name: payslip-service
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payslip-service
  template:
    metadata:
      labels:
        app: payslip-service
    spec:
      containers:
      - name: payslip-service
        image: localhost:5000/payslip-service:latest
        ports:
        - containerPort: 8080
