apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-manager-service
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-manager-service
  template:
    metadata:
      labels:
        app: db-manager-service
    spec:
      containers:
      - name: db-manager-service
        image: localhost:5000/db-manager:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
